### ISSUE TITLE
Promote %s to a standard specification?

### ISSUE THREAD

**Issue by zmwangx** [lestrrat-go/strftime#17]
I was writing docs on what strftime specs are supported for a project of mine using this library, so I went to look for where the specs originated. Turns out  they're from FreeBSD[1]/macOS[2] `strftime(3)`: the descriptions match word for word, and the lists of specs are the same with a few specs/categories missing here — POSIX locale extensions (`%E*`, `%O*`), glibc extensions, `%G`, `%g` and `%s`. I can understand not implementing `%G` and `%g`, they're weird (`%G` for 2019-12-31 => 2020), but `%s` is trivial and very widely supported and used, so it's a bit strange it has to be added as an extension, seems more like an accidental omission to me.

So what about promoting it to a standard spec? (The extension could of course be kept around for backward compatibility.) It's an easy change, I can submit a PR if you don't feel like spending time on this.

[1] https://www.freebsd.org/cgi/man.cgi?query=strftime&sektion=3
[2] https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/strftime.3.html

**Comment by lestrrat** [comment]
It has been a while, but IIRC the list was reduced to a strict subset of the POSIX specification because their behavior just varies so much depending on your source of truth.

One of the documents that I base this argument is [Perl's POSIX.pm documentation](https://metacpan.org/pod/POSIX), which states

> If you want your code to be portable, your format (fmt) argument should use only the conversion specifiers defined by the ANSI C standard (C89, to play safe). These are aAbBcdHIjmMpSUwWxXyYZ%

Now it is easy to include an extra specification, but the bigger question is: "what happens when somebody with a same request comes by? what are the criteria to decide what to include / what not to include?"

My personal take is that I want this project to be low maintenance, and I don't want to be involved in discussions to be convinced if a particular specification should be included, or should conform to the specs described in a version of manual that I have yet to find, etc.

So yeah, while given enough prodding I'm willing to be convinced otherwise, my initial answer is that I would rather make everything but the most basic functionalities optional, and %s was not on that particular list.

**Comment by zmwangx** [comment]
That’s fair.
